 # Portfolio settings
title: Casale Fine Art
description: Art form the adventures of Jordan Casale
email: artist@email

#MENU ITEM LIST

menu:
- {name: Works, url: '#works'}
- {name: Posts, url: '#posts'}
- {name: About, url: '#about'}

gallery:
- {name: 'Studio Works', tag: 'studio'}
- {name: 'Plein Air Works', tag: 'plein-air'}

clients:
- {avatar: 'client-1.JPG', name: 'Peggy Gardine', title: 'Collector', painting:  'painting-1.JPG' ,quote: '<p><strong>I purchased this 16x20 oil painting</strong> by Jordan Casale.  It is of a bridge with buildings behind it.  The painting reminds me of Europe because the buildings look like German apartments, especially the building in the rear.  The colors blend well with each other and fit my decor perfectly.  </p>'}
- {avatar: 'client-2.jpg', name: 'Millie Lacey', title: 'Collector', painting:  'painting-1.JPG' ,quote: '<p><strong>I purchased this 16x20 oil painting</strong> by Jordan Casale.  It is of a bridge with buildings behind it.  The painting reminds me of Europe because the buildings look like German apartments, especially the building in the rear.  The colors blend well with each other and fit my decor perfectly.  </p>'}
- {avatar: 'client-1.JPG', name: 'Callee Miller', title: 'Collector', painting:  'painting-1.JPG' ,quote: '<p><strong>I purchased this 16x20 oil painting</strong> by Jordan Casale.  It is of a bridge with buildings behind it.  The painting reminds me of Europe because the buildings look like German apartments, especially the building in the rear.  The colors blend well with each other and fit my decor perfectly.  </p>'}
- {avatar: 'client-1.JPG', name: 'Josh Dorn', title: 'Collector', painting:  'painting-1.JPG' ,quote: '<p><strong>I purchased this 16x20 oil painting</strong> by Jordan Casale.  It is of a bridge with buildings behind it.  The painting reminds me of Europe because the buildings look like German apartments, especially the building in the rear.  The colors blend well with each other and fit my decor perfectly.  </p>'}
- {avatar: 'client-1.JPG', name: 'Samantha Philbrick', title: 'Collector', painting:  'painting-1.JPG' ,quote: '<p><strong>I purchased this 16x20 oil painting</strong> by Jordan Casale.  It is of a bridge with buildings behind it.  The painting reminds me of Europe because the buildings look like German apartments, especially the building in the rear.  The colors blend well with each other and fit my decor perfectly.  </p>'}


#skill-icon:
#  - icon-palette.svg
#  - icon-path.svg
 # - icon-html.svg
 # - icon-sharpener.svg

# Change the site default images and content here!
logo: 'logo.svg'
bg-img: 'bg-img.jpg'

avatar: 'travitar.jpg'
blurb: <p><strong>Jordan loves to learn.</strong> Jordan was raised in Littleton, Colorado in the shadow of the foothills.  He and his family moved to Goodland 4 years ago to embrace a more community focused life.  Jordan has been painting for 5 years, but his history with art stretches back much farther.  He hopes to express the beauty of God’s creation in a singular moment that normally remains elusive and passes too quickly.
